### ISSUE TITLE
the dependency on xbmc.python could not be satisfied

### ISSUE THREAD

**Issue by kzolti** [vargalex/plugin.video.exoshark#2]
Kodi 18-ra az addont nem tudom telepíteni. 
the dependency on xbmc.python could not be satisfied

**Comment by vargalex** [comment]
A python a Kodi-val együtt kellene jöjjön, így a hibát a Kodi-n belül kellene keresni. Esetleg próbáld meg [ezt](https://livetvkodiserbia.com/kodi/zips/xbmc.python/xbmc.python-2.26.0.zip) telepíteni (még egyszer mondom, alapból telepítenie kellene a Kodi-nak).

**Comment by kzolti** [comment]
Van python 2 és 3 a gépemen, a Kodi viszont figyelmen kívül hagyja a 2-est úgy látom a logban:
_Addon 'xbmc.python' already present with higher version 3.0.0 at '/usr/share/kodi/addons/xbmc.python/' - other version 2.26.0 at '/home/zolti/.kodi/addons/xbmc.python/' will be ignored_
Azt hiszem az a baj, hogy a kiegészítő 2-es pythonra támaszkodik. Ezt találtam ezzel kapcsolatban:
https://kodi.wiki/view/Migration_to_Python_3

**Comment by vargalex** [comment]
Szia!

A Kodi 18 (Leia) nem hagyhatja figyelmen kívül a Python 2-t, lévén csak azt ismeri, a Python 3 a Kodi 19 (Matrix) verzióban jött be. De ezek alapján te Leia alá tettél fel 3.0.0 xbmc.python csomagot, vagy mégsem Kodi 18-at, hanem Kodi 19-et használsz. Utóbbival nem kompatibilis az Exoshark.

**Comment by kzolti** [comment]
Igazad van, 19.4 -et használok. Megpróbálom downgraddelni. 
Bocsi, hogy félrevezettelek köszönöm a segítséget.
